const propertyMap = {
  id: "wikidata_id",
  wu: "wikipedia_url",
  n: "name",
  by: "birth_year",
  bd: "birth_date",
  bp: "birth_place_name",
  dy: "death_year",
  dd: "death_date",
  dp: "death_place_name",
  cd: "article_created_date",
  al: "article_length",
  rv: "article_recent_views",
  te: "article_total_edits",
  re: "article_recent_edits",
};

export const ATTRIBUTE_LABELS = {
  ad: "academic_degree",
  ar: "award_received",
  cod: "cause_of_death",
  c: "conflict",
  co: "convicted_of",
  ed: "educated_at",
  eg: "ethnic_group",
  fw: "field_of_work",
  g: "gender",
  h: "handedness",
  hp: "honorific_prefix",
  md: "manner_of_death",
  mc: "medical_condition",
  mo: "member_of",
  nl: "native_language",
  o: "occupation",
  pi: "political_ideology",
  ph: "position_held",
  wv: "religion_or_worldview",
  sc: "social_classification",
}

export default ATTRIBUTE_LABELS;
